### ISSUE TITLE
'Pages' section of Report capped at 5?

### ISSUE THREAD

**Issue by juanbiberretta** [GoogleChromeLabs/web-vitals-report#10]
Hello! Love the app but would really benefit from being able to specify how many pages I want to see in the report. The documentation says: 

> It also includes a drill down of the top five countries and pages (by total number of Web Vitals events received), so you can see if certain pages or user populations perform better or worse than others.

I know for a fact we're sending web vitals info from thousands of pages, so not sure why I can only see five? Also curious as to how it choses said pages. Is it based off performance? They seem to be a mix of good and bad performing pages. 

Anyhow, any help would be much appreciated, thank you!

**Comment by philipwalton** [comment]
So, I understand this might not be the answer you were looking for, but part of [the intention](https://github.com/GoogleChromeLabs/web-vitals-report#:~:text=The%20app%20is%20available%20to%20use%20as%20a%20standalone%20tool%2C%20or%20you%20can%20fork%20it%20and%20customize%20it%20to%20your%20needs.) with releasing this tool was to provide developers with an example that they could fork and build on top of. It was never intended to be full-featured reporting tool.

Are you able to follow the instructions to [build and run the tool yourself](https://github.com/GoogleChromeLabs/web-vitals-report#build-and-run-the-app-locally)? If so then you could change [this line of code](https://github.com/GoogleChromeLabs/web-vitals-report/blob/380f197d79634fba1985f61744483c83280bde4d/src/js/charts.js#L164) from `.slice(0, 5)` to `.slice(0, 20)` (or whatever number you want).

I'll keep this issue open to track this feature request, but as I said our hope was that developers would build their own dashboards based on this example. My team unfortunately doesn't have the resources to actively maintain and develop this tool.

**Comment by juanbiberretta** [comment]
@philipwalton Thank you for thoughtful response! I see, that makes sense, I hadn't done that because I hoped I was just missing something obvious from the config. I'll give forking + running the tool myself a shot, cheers
