### ISSUE TITLE
Error on Submit : Failed to execute 'bound' on 'IDBKeyRange'

### ISSUE THREAD

**Issue by manojvignesh** [GoogleChromeLabs/web-vitals-report#15]
Oops, something went wrong!
Failed to execute 'bound' on 'IDBKeyRange': The parameter is not a valid key.

![image](https://user-images.githubusercontent.com/15259741/149912487-7d524d0f-8a5b-42de-b711-e9c45bf6a33a.png)

**Comment by philipwalton** [comment]
Can you give me a bit more information?
- What browser and version are you using?
- What report configuration have you set?

Can you also try clearing your storage and seeing if that fixes the issue?

**Comment by manojvignesh** [comment]
Browser: Chrome
Version: 97.0.4692.71 (Official Build) (arm64)

Config:
Choose date range: Last 7 days
Compare segments: New vs returning users.

Tried clearing the cache in all ways. cmd+r, cmd+Shift+r and empty cache and hard reload.
Recently switched from intel to m1 mac.

**Comment by philipwalton** [comment]
Thanks for that info. Some browsers don't support array-keys in IndexedDB, but given that you're using Chrome 97, that shouldn't be an issue...

Did you try clearing your storage using DevTools? (See this screenshot)
1. Click the "Clear site data" button in DevTools under _Application_ > _Storage_
2. Make sure the IndexedDB box is checked

<img width="1134" alt="Screen Shot 2022-01-19 at 9 46 09 AM" src="https://user-images.githubusercontent.com/326742/150186107-44a6e02f-3ad6-49bb-8c58-826360409950.png">

The fix I'm considering for this is to just clear the IndexedDB database if there are any errors reading to or writing to the store, but I want to confirm that that will actually fix your issue before I add that check.

**Comment by philipwalton** [comment]
I submitted #16, which I think should fix your issue. Please reply here if it doesn't.

**Comment by manojvignesh** [comment]
@philipwalton Sry for not replying sooner. Just verified and it's working now. Thanks a lot.
