### ISSUE TITLE
Field Data not gathering despite a lot of traffic

### ISSUE THREAD

**Issue by asawdwefr345terf** [GoogleChromeLabs/web-vitals-report#27]
I'm using the exact same code in 2 websites:

```
<script type="module">
import {onCLS, onFID, onLCP} from 'https://unpkg.com/web-vitals@3/dist/web-vitals.attribution.js?module';
function sendToGoogleAnalytics({name, delta, id, attribution}) {
 let debug_target;

  switch (name) {
    case 'CLS':
     debug_target = attribution.largestShiftTarget;
      break;
    case 'FID':
     debug_target = attribution.eventTarget;
      break;
    case 'LCP':
     debug_target = attribution.element;
      break;
  }
  
  gtag('event', name, {
    event_category: 'Web Vitals',
    event_label: id,
    value: Math.round(name === 'CLS' ? delta * 1000 : delta),
    non_interaction: true,
	dimension2: debug_target  });
}

onCLS(sendToGoogleAnalytics);
onFID(sendToGoogleAnalytics);
onLCP(sendToGoogleAnalytics);
</script>
```

1.  https://www.mycannabis.com
2.  https://trainingcoursematerial.com

The first website (mycannabis) is getting only 500 users per day out of which 40% are Chrome users

![image](https://github.com/GoogleChromeLabs/web-vitals-report/assets/78820188/1cc9207d-3add-4d56-aeea-ed2739b44579)

![image](https://github.com/GoogleChromeLabs/web-vitals-report/assets/78820188/a3a3c9b8-9a23-4f75-899e-edc1f4e7b919)

The second website (trainingcourse) is getting 800+ users per day out of which 60% are Chrome users

![image](https://github.com/GoogleChromeLabs/web-vitals-report/assets/78820188/154fb638-a26c-48a0-85a6-5033a7e95f36)

![image](https://github.com/GoogleChromeLabs/web-vitals-report/assets/78820188/d68a20db-9118-4aa1-b963-976eb4666063)

Both of the websites are collecting web vitals data when I check in Network Tab:

![image](https://github.com/GoogleChromeLabs/web-vitals-report/assets/78820188/5aea7051-b93e-43b4-a6ce-3a1509496b3c)

The first website, despite getting less traffic, less % of Chrome users, less % of Andriod users, gets A LOT of data collected in Web Vitals Report app:

![image](https://github.com/GoogleChromeLabs/web-vitals-report/assets/78820188/88c59955-fc87-4892-972a-722a40a94679)

Yet, the second website with more traffic, more % of Chrome and Andriod users, gets little to non-existent data collected when compared to the same date period:

![image](https://github.com/GoogleChromeLabs/web-vitals-report/assets/78820188/bbcc21d9-b4b8-4089-b7ac-def3d21a6008)

_Both of the UA analytics property are functioning and not retired yet._

**Comment by tunetheweb** [comment]
I'm getting the below error on your https://trainingcoursematerial.com/ site:

<img width="454" alt="image" src="https://github.com/GoogleChromeLabs/web-vitals-report/assets/10931297/cff12bb6-53bc-465c-a38f-3d4739a31205">

This is because you are defining `gtag()` after the script.

I'm going to close this issue as general JavaScript debugging is outside the scope of this repo.

**Comment by asawdwefr345terf** [comment]
If you think gtag() if preventing the collection of data then I should get no data at all. Why do I get some data then?

I have a third website (https://www.securities.io/) which has the same gtag() warning in console yet it collects a lot of field data.

So it might be there is something else?
