### ISSUE TITLE
Provide examples to collect Web Vitals from AMP enabled Websites using GA and GTM

### ISSUE THREAD

**Issue by raja-anbazhagan** [GoogleChromeLabs/web-vitals-report#3]
I use Google Tag Manager for AMP enabled wordpress site. And it currently has a generic page view tracking thanks to Google Site Kit Plugin.

I can't place web-vitals script from GTM anymore as it is not supported in AMP container. But I recently found out that you can use amp-analytics with built in variables like this.

```
<amp-analytics type="googleanalytics">
	<script type="application/json">
        {
          "vars": {
            "gtag_id": "UA-XXXXXXXXX-X",
            "config": {
              "UA-XXXXXXXXX-X": {
                "groups": "default"
              }
            }
          },
          "triggers": {
            "default pageview": {
              "on": "visible",
              "request": "pageview",
              "vars": {
                "title": "{{title}}"
              },
              "extraUrlParams": {
                "lcp": "${largestContentfulPaint}",
                "cls": "${cumulativeLayoutShift}",
                "fid": "${firstInputDelay}"
              }
            }
          }
        }	
	</script>
</amp-analytics>
```

But honestly, I have no idea how this value gets mapped on the google analytics. Also, I don't have enough knowledge to fit the same setting in Google Tag manager. 

So If you could add instructions for AMP enabled websites as well it would be a great addition to the documentation. 

The AMP enabled websites are only 0.1% of total websites in the web. But people like me switched to AMP mainly for Core-Web-Vitals benefit. So If you could provide a consistent way to test the results, It would be helpful.

**Comment by philipwalton** [comment]
Sorry for the slow response. I'm actually not familiar with how AMP reports this data through GTM either. @kristoferbaxter any idea who we can route this to?

**Comment by kristoferbaxter** [comment]
I'm on my phone right now, but will ask Mica from the AMP Project to take a look tomorrow.

Know there is a guide for supporting CWV metrics reporting, but am less familiar with GA integration.

**Comment by raja-anbazhagan** [comment]
The example in my issue description is taken from AMP documentation. Even though it is helpful in terms of sending these metrics as custom dimensions, I was hoping to send these metrics as Events. This way I could plot them directly in https://web-vitals-report.web.app/. 

With that being said, I raised this request when AMP was lacking features to convert these decimal points to integers by multiplying them by 1000 or rounding them. But I and @micajuine-ho worked this out via PR ampproject/amphtml#33383 a few weeks back.

This is how I use the amp-analytics module on my website at the moment.

```xml
<amp-analytics  type="googleanalytics">
<script type="application/json">
{
  "vars": {
    "account": "UA-123456-1"
  },
  "triggers": {
    "capture CLS": {
      "on": "visible",
      "request": "event",
      "vars": {
        "eventCategory": "Web Vitals",
        "eventAction": "CLS",
        "eventLabel": "${clientId}-${pageViewId}-CLS",
        "eventValue": "$CALC(${cumulativeLayoutShift},1000,multiply,true)"
      }
    },
    "capture FID": {
      "on": "visible",
      "request": "event",
      "vars": {
        "eventCategory": "Web Vitals",
        "eventAction": "FID",
        "eventLabel": "${clientId}-${pageViewId}-FID",
        "eventValue": "$CALC(${firstInputDelay},0,add,true)"
      }
    },
    "capture LCP": {
      "on": "visible",
      "request": "event",
      "vars": {
        "eventCategory": "Web Vitals",
        "eventAction": "LCP",
        "eventLabel": "${clientId}-${pageViewId}-LCP",
        "eventValue": "$CALC(${largestContentfulPaint},0,add,true)"
      }
    }
  }
}
</script>
</amp-analytics>
```

We just need to document this somewhere.

**Comment by raja-anbazhagan** [comment]
And for Google Tag Manager for AMP, the AMP Variables setup in GTM escapes the `$` signs by default.

![image](https://user-images.githubusercontent.com/8947215/117241687-54030480-ae51-11eb-9403-6fcdfd306a73.png)

Guess we can ignore GTP for now.

**Comment by tunetheweb** [comment]
Closing this as seems less related to this repo and more for AMP.
