### ISSUE TITLE
Field Data problem with GA

### ISSUE THREAD

**Issue by asawdwefr345terf** [GoogleChromeLabs/web-vitals-report#47]
Hi Barry!

We are using your code on our Shopify store to measure field data Core Web Vitals through the Web Vitals Report app. It's a must have!

When we place the Analytics code **after** the web vitals library, it doesn't sends the data  to GA.

When we place the Analytics code **before** the web vitals library, it works and sends the data to our GA.

The problem is, in Shopify, the GA code is buried in with other tracking scripts like this:

```
trekkie.load(
      {"Trekkie":{"appName":"storefront","development":false,"defaultAttributes":{"shopId":9903636546,"isMerchantRequest":null,"themeId":136834416853,"themeCityHash":"11864794253938457520","contentLanguage":"en","currency":"USD"},"isServerSideCookieWritingEnabled":true,"monorailRegion":"shop_domain"},"Google Analytics":{"trackingId":"UA-146128799-1","domain":"auto","siteSpeedSampleRate":"10","enhancedEcommerce":true,"doubleClick":true,"includeSearch":true},"Facebook Pixel":{"pixelIds":["678075513264158"],"agent":"plshopify1.2"},"Pinterest Pixel":{"pixelId":"2612622350597"},"Google Gtag Pixel":{"conversionId":"G-KQKGHFJ06K","eventLabels":[{"type":"search","action_label":["G-KQKGHFJ06K","AW-708062442\/lKkdCO2DvKsBEOrZ0NEC"]},{"type":"begin_checkout","action_label":["G-KQKGHFJ06K","AW-708062442\/y3NFCOqDvKsBEOrZ0NEC"]},{"type":"view_item","action_label":["G-KQKGHFJ06K","AW-708062442\/OtSXCOSDvKsBEOrZ0NEC","MC-1FB355FTP1"]},{"type":"purchase","action_label":["G-KQKGHFJ06K","AW-708062442\/yhhZCPLMuI8YEOrZ0NEC","MC-1FB355FTP1"]},{"type":"page_view","action_label":["G-KQKGHFJ06K","AW-708062442\/yyTGCN6DvKsBEOrZ0NEC","MC-1FB355FTP1"]},{"type":"add_payment_info","action_label":["G-KQKGHFJ06K","AW-708062442\/0B6MCPCDvKsBEOrZ0NEC"]},{"type":"add_to_cart","action_label":["G-KQKGHFJ06K","AW-708062442\/uHNtCOeDvKsBEOrZ0NEC"]}],"targetCountry":"US"},"Session Attribution":{},"S2S":{"facebookCapiEnabled":true,"facebookAppPixelId":"678075513264158","source":"trekkie-storefront-renderer"}}
    );
```

Since it's very hard to extract only the Google Analytics code from the above and place it before (above) the web vitals library code.

What I do is leave the above GA code as it is (since I'm afraid to mess with the mess) and on top of it, add GA code from Google Analytics:

![image](https://github.com/GoogleChromeLabs/web-vitals-report/assets/78820188/c5a91467-1892-4757-9595-4700f6ccc4b9)

Now we have two GA code with the same Tracking ID as you can tell from the source code of the website: https://www.stunningcanvasprints.com/

and it works because now, we do get the field data in our analytics except here's 1 strange issue: 

![image](https://github.com/GoogleChromeLabs/web-vitals-report/assets/78820188/9f54d08b-4248-4272-9971-cc3059c3c1f7)

Although, our Analytics collects all sort of data perfectly fine plus we now collect the Field Data too but, the Bounce Rate drops.

This happens on every Shopify store when we place the clean GA code before the web vitals library. 

This does not happens on WordPress.

Please advise, how can we use your code on Shopify store without affecting Bounce Rate tracking?

TIA

**Comment by tunetheweb** [comment]
Sorry I don't know about trekkie so can't advise and this is out of scope for this repo.

You can disable the default page view that happens when initialising GA via GTAG so that might be what you need to do here if trekkie is already initialising this: https://developers.google.com/analytics/devguides/collection/ga4/views?client_type=gtag#disable_pageview_measurement
