### ISSUE TITLE
Add support for TTFB and FCP

### ISSUE THREAD

**Issue by groseler** [GoogleChromeLabs/web-vitals-report#5]
Since TTFB and FCP are also metrics from web core vitals api, is it possible to be added to the report?

Thank you

**Comment by philipwalton** [comment]
At the moment, neither of these metrics have recommended thresholds published, so it wouldn't be possible to add them without significantly changing how the data in the report is design/presented.

If you'd like this data, my recommendation is to fork the report and [build a version customized to your needs](https://github.com/GoogleChromeLabs/web-vitals-report#build-and-run-the-app-locally). The intention of this report was always to serve as a model for teams to build their own custom reporting tool. The public version of this report has some basic features, but I do not plan to add a lot of new features in the future.
